import React from 'react';
import { Lock, ShieldCheck } from 'lucide-react';

interface PrivacyPageProps {
  navigate: (path: string) => void;
}

export const PrivacyPage: React.FC<PrivacyPageProps> = ({ navigate }) => {
  return (
    <div className="bg-white text-slate-900 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <div className="border-b border-slate-200 pb-6 space-y-2">
          <div className="text-xs font-bold uppercase tracking-wider text-[#0088cc]">
            Data Protection & Security
          </div>
          <h1 className="text-3xl font-extrabold text-slate-900">Privacy Policy</h1>
          <p className="text-xs text-slate-500">Effective Date: February 2025</p>
        </div>

        <div className="space-y-6 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900">1. Information We Collect</h2>
            <p>
              When you register and use TeleBot Host, we collect only the necessary information required to operate your hosting account:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Account data (Name, email address, optional Telegram username)</li>
              <li>Encrypted configuration variables and Telegram Bot tokens provided by you</li>
              <li>Container runtime metrics (CPU, RAM, disk usage) to enforce resource allocations</li>
              <li>Transaction receipts processed via Cashfree Payments</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900">2. Encryption & Bot Token Security</h2>
            <p>
              All Telegram Bot API tokens, database passwords, and environment secret variables are stored using industry-standard AES-256 encryption. Tokens are only decrypted in memory inside your isolated container process and are never accessible to third parties or logged in plain text.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900">3. Telegram Message Privacy</h2>
            <p>
              TeleBot Host acts purely as an infrastructure host. We <strong>do not intercept, inspect, store, or sell</strong> the content of chat messages, media files, or user interactions routed through your Telegram bots. All communication between your bot and Telegram servers is encrypted using official Telegram Bot API protocols.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900">4. Log Retention Policy</h2>
            <p>
              Live container logs generated by your bot's <code>stdout</code> and <code>stderr</code> are retained in an in-memory buffer for debugging purposes for up to 7 days, after which they are automatically purged.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900">5. Your Data Rights (GDPR & CCPA)</h2>
            <p>
              You maintain complete ownership of your code, database files, and media. You may request account deletion, data export, or bot termination at any time through your dashboard or by emailing privacy@telebothost.io.
            </p>
          </section>
        </div>

        <div className="pt-6 border-t border-slate-200 flex items-center justify-between">
          <button
            onClick={() => navigate('/terms')}
            className="text-xs font-semibold text-[#0088cc] hover:underline"
          >
            ← View Terms of Service
          </button>
          <button
            onClick={() => navigate('/contact')}
            className="text-xs font-semibold text-slate-700 hover:text-slate-900"
          >
            Contact Privacy Officer
          </button>
        </div>
      </div>
    </div>
  );
};
